# Generated by Django 5.1.7 on 2025-03-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmationcode',
            old_name='user_id',
            new_name='username',
        ),
    ]
