# Generated by Django 5.1.7 on 2025-03-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_id_confirmationcode_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmationcode',
            old_name='username',
            new_name='user',
        ),
    ]
