version: '3'

services:
  afisha_api:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "3000:8000" #host:container
    depends_on:
      - afisha_db
  afisha_db:
    image: 'postgres:14'
    env_file:
    - '.env'
    environment:
      POSTGRES_DB: '${NAME_DB}'
      POSTGRES_USER: '${USER_DB}'
      POSTGRES_PASSWORD: '${PASSWORD_DB}'
    volumes:
      - 'afisha_data:/var/lib/postgresql/data'
volumes:
  afisha_data:

